Сбор телеметрии
Byndyusoft/Byndyusoft.Telemetry pull request #1
Opened 2023-12-26 08:26 UTC by Rinatich

- Сбор статической телеметрии сервиса
- Сбор телеметрии из объектов
- Инструмент для обогащения свойств логов в контексте асинхронного вызова
- Инструмент для обогащения ресурса OpenTelemetry статической информацией
- Инструмент для обогащения свойств логов статической информацией

2024-01-18 20:16 UTC, litichevskiydv requested changes

2024-01-18 20:16 UTC, litichevskiydv commented on Byndyusoft.Telemetry.sln.DotSettings
> +﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
Предлагаю заюзать [настройки из шаблона API](https://github.com/Byndyusoft/byndyusoft-templates-api/blob/main/templates/Byndyusoft.DotNet.Web.ProjectTemplate.sln.DotSettings).

2024-01-18 20:16 UTC, litichevskiydv commented on example/TestApi/Program.cs
> +            options.Filter = context => context.Request.Path.StartsWithSegments("/swagger") == false;
Напршивается фильтр для игнора сервисных роутов типа `swagger`, `metrics`, etc.

2024-01-18 20:16 UTC, litichevskiydv commented on src/Telemetry.Logging.Serilog/Enrichers/TelemetryStaticTelemetryItemsEnricher.cs
> +            logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty(telemetryItem.Name.Replace('.', '_'),
`Replace('.', '_')` может сделать из этого расширение для форматирования имен?

2024-01-18 20:16 UTC, litichevskiydv commented on src/Telemetry/Providers/Interface/IStaticTelemetryItemProvider.cs
> +    public interface IStaticTelemetryItemProvider
Думаю, стоит перенести его в сборку абстракций, чтобы потребители могли добавлять свои провайдеры

2024-01-23 08:28 UTC, Rinatich commented on example/TestApi/Program.cs
> +            options.Filter = context => context.Request.Path.StartsWithSegments("/swagger") == false;
фильтр для чего? Здесь это тестовый апи проект.

2024-01-23 08:39 UTC, Rinatich commented on Byndyusoft.Telemetry.sln.DotSettings
> +﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
++

2024-01-23 08:43 UTC, Rinatich commented on src/Telemetry/Providers/Interface/IStaticTelemetryItemProvider.cs
> +    public interface IStaticTelemetryItemProvider
++

2024-01-23 08:48 UTC, Rinatich commented on src/Telemetry.Logging.Serilog/Enrichers/TelemetryStaticTelemetryItemsEnricher.cs
> +            logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty(telemetryItem.Name.Replace('.', '_'),
++

2024-01-25 10:52 UTC, litichevskiydv approved these changes

2024-02-22 05:22 UTC, govorovvs requested changes

2024-02-22 05:22 UTC, govorovvs commented on src/Telemetry/Reflection/PropertyItem.cs
> +        public PropertyItem(string propertyName, object? value)
чем отличается от TelemetryItem?

2024-03-13 07:55 UTC, Mblkolo requested changes

2024-03-13 07:55 UTC, Mblkolo commented on README.md
> +[![License](https://img.shields.io/badge/License-Apache--2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)
Не понятно какие проблемы решает и зачем нужна эта репа.

2024-03-13 07:55 UTC, Mblkolo commented on src/Telemetry.Logging/LogPropertyDataAccessor.cs
> +        private class EventDataHolder
Холдер точно нужен? В HttpContextAccessor он нужен чтобы стирать значение в любой момент.

2024-03-13 07:55 UTC, Mblkolo commented on src/Telemetry/Reflection/PropertyItem.cs
> +        public PropertyItem(string propertyName, object? value)
Семантикой

2024-05-06 11:00 UTC, Mblkolo approved these changes

2024-05-08 05:53 UTC, merged